 export const data= [
        {
            "product_id": "45010",
            "product": "Бепантен 5% 30 г мазь",
            "supplier_id": null,
            "product_code": "02854",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "329",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1686131335",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "0",
            "ab__stickers_generated_ids": null,
            "guid": "a807446b-1889-11e0-bbed-881d2b1000c3",
            "1c_title": "БЕПАНТЕН 5% 30г мазь",
            "true_photo": "N",
            "product_group": "5",
            "active_substance_id": "3060",
            "pharm_group_id": "475",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "c801c308-7a21-4f9b-b010-040f5b7281fb",
            "scode": "11430",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "680",
            "category_ids": [
                1861,
                1862,
                1886
            ],
            "seo_name": "bepanten-5-30-0-maz",
            "seo_path": "1646/1778/1886",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "46651",
            "main_category": 1886,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "39372",
                "image_id": "0",
                "detailed_id": "41236",
                "position": "1",
                "object_id": "45010",
                "object_type": "product",
                "detailed": {
                    "object_id": "45010",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/41/Бепантен_мазь_30г.webp",
                    "alt": "",
                    "image_x": "1780",
                    "image_y": "926",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/41/Бепантен_мазь_30г.webp",
                    "https_image_path": "https://neman.kg/images/detailed/41/Бепантен_мазь_30г.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/41/Бепантен_мазь_30г.webp",
                    "relative_path": "detailed/41/Бепантен_мазь_30г.webp"
                }
            },
            "base_price": "680",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "664": {
                    "feature_id": "664",
                    "value": "",
                    "value_int": null,
                    "variant_id": "2889",
                    "feature_type": "S",
                    "internal_name": "Условия отпуска из аптек",
                    "description": "Условия отпуска из аптек",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Без рецепта",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "360-2889",
                    "variants": {
                        "2889": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "2889",
                            "variant": "Без рецепта",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "40071",
            "product": "Марсианчики Иммунактив 30 Таблеток",
            "supplier_id": null,
            "product_code": "31952",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "86",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1685748023",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "c87bd2b1-be12-11e8-80c5-c83a35d8dfd0",
            "1c_title": "МАРСИАНЦИ ИММУНО №30 табл",
            "true_photo": "N",
            "product_group": "1",
            "active_substance_id": "2153",
            "pharm_group_id": "188",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "63087d27-e17f-11e3-a4db-003067a403f0",
            "scode": "80484035",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "377",
            "category_ids": [
                1657,
                1670,
                1669,
                1686
            ],
            "seo_name": "marsianci-immuno-30-tabl",
            "seo_path": "1657/1683/1686",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "41574",
            "main_category": 1686,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "20029",
                "image_id": "0",
                "detailed_id": "22065",
                "position": "0",
                "object_id": "40071",
                "object_type": "product",
                "detailed": {
                    "object_id": "40071",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/22/Марсианчики_таблетки_картинка_-.webp",
                    "alt": "",
                    "image_x": "1464",
                    "image_y": "1969",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/22/Марсианчики_таблетки_картинка_-.webp",
                    "https_image_path": "https://neman.kg/images/detailed/22/Марсианчики_таблетки_картинка_-.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/22/Марсианчики_таблетки_картинка_-.webp",
                    "relative_path": "detailed/22/Марсианчики_таблетки_картинка_-.webp"
                }
            },
            "base_price": "377",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "734": {
                    "feature_id": "734",
                    "value": "",
                    "value_int": null,
                    "variant_id": "5664",
                    "feature_type": "S",
                    "internal_name": "Бренд",
                    "description": "Бренд",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Марсианчики",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "369-5664",
                    "variants": {
                        "5664": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "5664",
                            "variant": "Марсианчики",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "61075",
            "product": "Синулан форте №30 таблетки",
            "supplier_id": null,
            "product_code": "36726",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "20",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1637337630",
            "updated_timestamp": "1685695563",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "6d0ebc5f-386d-11ec-80c9-503eaa14b983",
            "1c_title": "СИНУЛАН ФОРТЕ №30 табл",
            "true_photo": "N",
            "product_group": "1",
            "active_substance_id": "2242",
            "pharm_group_id": "490",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "63087d27-e17f-11e3-a4db-003067a403f0",
            "scode": null,
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "185",
            "category_ids": [
                1737
            ],
            "seo_name": "sinulan-forte-30-tabl",
            "seo_path": "1657/1659/1737",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "63475",
            "main_category": 1737,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "38934",
                "image_id": "0",
                "detailed_id": "40840",
                "position": "0",
                "object_id": "61075",
                "object_type": "product",
                "detailed": {
                    "object_id": "61075",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/40/6051249251.webp",
                    "alt": "",
                    "image_x": "750",
                    "image_y": "1000",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/40/6051249251.webp",
                    "https_image_path": "https://neman.kg/images/detailed/40/6051249251.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/40/6051249251.webp",
                    "relative_path": "detailed/40/6051249251.webp"
                }
            },
            "base_price": "185",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": [],
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "44207",
            "product": "Ренни №24 жевательные таблетки со вкусом апельсина",
            "supplier_id": null,
            "product_code": "09616",
            "product_type": "P",
            "status": "H",
            "company_id": "9",
            "list_price": "0",
            "amount": "0",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1684319133",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "0",
            "ab__stickers_generated_ids": null,
            "guid": "20783e9a-aa0c-11e1-94be-003067a403f0",
            "1c_title": "РЕННИ №24 жев.табл С АПЕЛЬСИНОВЫМ ВКУСОМ",
            "true_photo": "N",
            "product_group": "5",
            "active_substance_id": "4321",
            "pharm_group_id": "827",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "c801c308-7a21-4f9b-b010-040f5b7281fb",
            "scode": "10324",
            "brand": null,
            "handpopularity": "100000",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "310",
            "category_ids": [
                1804,
                1651,
                1646,
                1805
            ],
            "seo_name": "renni-24-zhevatelnyy-tabletki-s-apelsinovym-vkusom",
            "seo_path": "1646/1651/1805",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "45772",
            "main_category": 1805,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "39377",
                "image_id": "0",
                "detailed_id": "41241",
                "position": "1",
                "object_id": "44207",
                "object_type": "product",
                "detailed": {
                    "object_id": "44207",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/41/Ренни,_таб.жев._с_апельсиновым_вкусом_24.webp",
                    "alt": "",
                    "image_x": "2000",
                    "image_y": "2000",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/41/Ренни,_таб.жев._с_апельсиновым_вкусом_24.webp",
                    "https_image_path": "https://neman.kg/images/detailed/41/Ренни,_таб.жев._с_апельсиновым_вкусом_24.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/41/Ренни,_таб.жев._с_апельсиновым_вкусом_24.webp",
                    "relative_path": "detailed/41/Ренни,_таб.жев._с_апельсиновым_вкусом_24.webp"
                }
            },
            "base_price": "310",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "664": {
                    "feature_id": "664",
                    "value": "",
                    "value_int": null,
                    "variant_id": "2889",
                    "feature_type": "S",
                    "internal_name": "Условия отпуска из аптек",
                    "description": "Условия отпуска из аптек",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Без рецепта",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "360-2889",
                    "variants": {
                        "2889": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "2889",
                            "variant": "Без рецепта",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "45192",
            "product": "Терафлекс   Хондрокрем  Форте 30г",
            "supplier_id": null,
            "product_code": "33749",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "6",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1685695977",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": null,
            "ab__stickers_generated_ids": null,
            "guid": "7014fc52-5e8e-11ea-80e7-c83a35d8dfd0",
            "1c_title": "ТЕРАФЛЕКС ХОНДРОКРЕМ ФОРТЕ 30г",
            "true_photo": "N",
            "product_group": "5",
            "active_substance_id": "2801",
            "pharm_group_id": "473",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "c801c308-7a21-4f9b-b010-040f5b7281fb",
            "scode": "",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "565",
            "category_ids": [
                1857,
                1812,
                1770,
                1852
            ],
            "seo_name": "terafleks-hondrokrem-forte-30g",
            "seo_path": "1646/1812/1852",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "46841",
            "main_category": 1852,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "39380",
                "image_id": "0",
                "detailed_id": "41244",
                "position": "1",
                "object_id": "45192",
                "object_type": "product",
                "detailed": {
                    "object_id": "45192",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/41/Терафлекс_Хондрокрем_Форте,_крем_30г.webp",
                    "alt": "",
                    "image_x": "1440",
                    "image_y": "1440",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/41/Терафлекс_Хондрокрем_Форте,_крем_30г.webp",
                    "https_image_path": "https://neman.kg/images/detailed/41/Терафлекс_Хондрокрем_Форте,_крем_30г.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/41/Терафлекс_Хондрокрем_Форте,_крем_30г.webp",
                    "relative_path": "detailed/41/Терафлекс_Хондрокрем_Форте,_крем_30г.webp"
                }
            },
            "base_price": "565",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": [],
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "53124",
            "product": "Vizit, презервативы, классические, 3 шт",
            "supplier_id": null,
            "product_code": "07352",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "108",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1686198981",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "451b9aa1-61d7-11e1-8363-003067a403f0",
            "1c_title": "ПРЕЗ VIZIT №3 КЛАССИЧЕСКИЕ",
            "true_photo": "N",
            "product_group": "9",
            "active_substance_id": "3393",
            "pharm_group_id": "28",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "151699f5-fa32-496b-8da9-0ffde5fd9cc1",
            "scode": "3711",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "120",
            "category_ids": [
                2145
            ],
            "seo_name": "prezervativy-vizit-3-klassicheskie",
            "seo_path": "1763/1831/2145",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "55023",
            "main_category": 2145,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "28523",
                "image_id": "0",
                "detailed_id": "30560",
                "position": "0",
                "object_id": "53124",
                "object_type": "product",
                "detailed": {
                    "object_id": "53124",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/30/vizit-classic_vpkw-jo.webp",
                    "alt": "",
                    "image_x": "500",
                    "image_y": "500",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/30/vizit-classic_vpkw-jo.webp",
                    "https_image_path": "https://neman.kg/images/detailed/30/vizit-classic_vpkw-jo.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/30/vizit-classic_vpkw-jo.webp",
                    "relative_path": "detailed/30/vizit-classic_vpkw-jo.webp"
                }
            },
            "base_price": "120",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "734": {
                    "feature_id": "734",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4296",
                    "feature_type": "S",
                    "internal_name": "Бренд",
                    "description": "Бренд",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Vizit",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "369-4296",
                    "variants": {
                        "4296": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4296",
                            "variant": "Vizit",
                            "image_pairs": false
                        }
                    }
                },
                "665": {
                    "feature_id": "665",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4297",
                    "feature_type": "S",
                    "internal_name": "Вид",
                    "description": "Вид",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Классические",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "365-4297",
                    "variants": {
                        "4297": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4297",
                            "variant": "Классические",
                            "image_pairs": false
                        }
                    }
                },
                "736": {
                    "feature_id": "736",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4295",
                    "feature_type": "S",
                    "internal_name": "Объём",
                    "description": "Объём",
                    "prefix": "",
                    "suffix": "",
                    "variant": "3 шт",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "364-4295",
                    "variants": {
                        "4295": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4295",
                            "variant": "3 шт",
                            "image_pairs": false
                        }
                    }
                },
                "737": {
                    "feature_id": "737",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4290",
                    "feature_type": "S",
                    "internal_name": "Тип продукта",
                    "description": "Тип продукта",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Презервативы",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "363-4290",
                    "variants": {
                        "4290": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4290",
                            "variant": "Презервативы",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "53190",
            "product": "Vizit, презервативы, увеличенного размера, 3 шт",
            "supplier_id": null,
            "product_code": "02636",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "107",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1686198990",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "eca6fed8-c483-11df-a63c-8000600fe800",
            "1c_title": "ПРЕЗ VIZIT №3 УВЕЛИЧЕННОГО РАЗМЕРА",
            "true_photo": "N",
            "product_group": "9",
            "active_substance_id": "3393",
            "pharm_group_id": "28",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "151699f5-fa32-496b-8da9-0ffde5fd9cc1",
            "scode": "9287",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "120",
            "category_ids": [
                2145
            ],
            "seo_name": "prezervativy-vizit-3-uvelichennogo-razmera",
            "seo_path": "1763/1831/2145",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "55089",
            "main_category": 2145,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "28584",
                "image_id": "0",
                "detailed_id": "30621",
                "position": "0",
                "object_id": "53190",
                "object_type": "product",
                "detailed": {
                    "object_id": "53190",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/30/a1fd53a58cae8b696d9fa90b710e3432.webp",
                    "alt": "",
                    "image_x": "500",
                    "image_y": "500",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/30/a1fd53a58cae8b696d9fa90b710e3432.webp",
                    "https_image_path": "https://neman.kg/images/detailed/30/a1fd53a58cae8b696d9fa90b710e3432.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/30/a1fd53a58cae8b696d9fa90b710e3432.webp",
                    "relative_path": "detailed/30/a1fd53a58cae8b696d9fa90b710e3432.webp"
                }
            },
            "base_price": "120",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "734": {
                    "feature_id": "734",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4296",
                    "feature_type": "S",
                    "internal_name": "Бренд",
                    "description": "Бренд",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Vizit",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "369-4296",
                    "variants": {
                        "4296": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4296",
                            "variant": "Vizit",
                            "image_pairs": false
                        }
                    }
                },
                "665": {
                    "feature_id": "665",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4313",
                    "feature_type": "S",
                    "internal_name": "Вид",
                    "description": "Вид",
                    "prefix": "",
                    "suffix": "",
                    "variant": "XXL",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "365-4313",
                    "variants": {
                        "4313": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4313",
                            "variant": "XXL",
                            "image_pairs": false
                        }
                    }
                },
                "736": {
                    "feature_id": "736",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4295",
                    "feature_type": "S",
                    "internal_name": "Объём",
                    "description": "Объём",
                    "prefix": "",
                    "suffix": "",
                    "variant": "3 шт",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "364-4295",
                    "variants": {
                        "4295": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4295",
                            "variant": "3 шт",
                            "image_pairs": false
                        }
                    }
                },
                "737": {
                    "feature_id": "737",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4290",
                    "feature_type": "S",
                    "internal_name": "Тип продукта",
                    "description": "Тип продукта",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Презервативы",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "363-4290",
                    "variants": {
                        "4290": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4290",
                            "variant": "Презервативы",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "53189",
            "product": "Vizit, презервативы, ребристые, 3 шт",
            "supplier_id": null,
            "product_code": "02639",
            "product_type": "P",
            "status": "H",
            "company_id": "9",
            "list_price": "0",
            "amount": "0",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1686301124",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "eca6fee4-c483-11df-a63c-8000600fe800",
            "1c_title": "ПРЕЗ VIZIT №3 РЕБРИСТЫЕ (С КОЛЬЦАМИ)",
            "true_photo": "N",
            "product_group": "9",
            "active_substance_id": "3393",
            "pharm_group_id": "28",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "151699f5-fa32-496b-8da9-0ffde5fd9cc1",
            "scode": "3712",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "120",
            "category_ids": [
                2145
            ],
            "seo_name": "prezervativy-vizit-3-rebristye",
            "seo_path": "1763/1831/2145",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "55088",
            "main_category": 2145,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "28583",
                "image_id": "0",
                "detailed_id": "30620",
                "position": "0",
                "object_id": "53189",
                "object_type": "product",
                "detailed": {
                    "object_id": "53189",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/30/34df960d78c2b818ec294075158268d3.webp",
                    "alt": "",
                    "image_x": "500",
                    "image_y": "500",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/30/34df960d78c2b818ec294075158268d3.webp",
                    "https_image_path": "https://neman.kg/images/detailed/30/34df960d78c2b818ec294075158268d3.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/30/34df960d78c2b818ec294075158268d3.webp",
                    "relative_path": "detailed/30/34df960d78c2b818ec294075158268d3.webp"
                }
            },
            "base_price": "120",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "734": {
                    "feature_id": "734",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4296",
                    "feature_type": "S",
                    "internal_name": "Бренд",
                    "description": "Бренд",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Vizit",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "369-4296",
                    "variants": {
                        "4296": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4296",
                            "variant": "Vizit",
                            "image_pairs": false
                        }
                    }
                },
                "665": {
                    "feature_id": "665",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4302",
                    "feature_type": "S",
                    "internal_name": "Вид",
                    "description": "Вид",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Ребристые",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "365-4302",
                    "variants": {
                        "4302": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4302",
                            "variant": "Ребристые",
                            "image_pairs": false
                        }
                    }
                },
                "736": {
                    "feature_id": "736",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4295",
                    "feature_type": "S",
                    "internal_name": "Объём",
                    "description": "Объём",
                    "prefix": "",
                    "suffix": "",
                    "variant": "3 шт",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "364-4295",
                    "variants": {
                        "4295": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4295",
                            "variant": "3 шт",
                            "image_pairs": false
                        }
                    }
                },
                "737": {
                    "feature_id": "737",
                    "value": "",
                    "value_int": null,
                    "variant_id": "4290",
                    "feature_type": "S",
                    "internal_name": "Тип продукта",
                    "description": "Тип продукта",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Презервативы",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "363-4290",
                    "variants": {
                        "4290": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "4290",
                            "variant": "Презервативы",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "44220",
            "product": "Боботик 30 мл капли",
            "supplier_id": null,
            "product_code": "02776",
            "product_type": "P",
            "status": "A",
            "company_id": "9",
            "list_price": "0",
            "amount": "303",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1686042390",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "0",
            "ab__stickers_generated_ids": null,
            "guid": "3eafb93e-da7d-11df-bbb1-b60da1a03f41",
            "1c_title": "БОБОТИК 30мл капли",
            "true_photo": "N",
            "product_group": "5",
            "active_substance_id": "4487",
            "pharm_group_id": "415",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "e7868832-6cce-11e0-9a81-0019214aecd7",
            "scode": "80467637",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "315",
            "category_ids": [
                1651
            ],
            "seo_name": "bobotik-30ml-kapli",
            "seo_path": "1646/1651",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "45785",
            "main_category": 1651,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "20963",
                "image_id": "0",
                "detailed_id": "22999",
                "position": "0",
                "object_id": "44220",
                "object_type": "product",
                "detailed": {
                    "object_id": "44220",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/22/bobotik.webp",
                    "alt": "",
                    "image_x": "400",
                    "image_y": "400",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/22/bobotik.webp",
                    "https_image_path": "https://neman.kg/images/detailed/22/bobotik.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/22/bobotik.webp",
                    "relative_path": "detailed/22/bobotik.webp"
                }
            },
            "base_price": "315",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": {
                "1060": {
                    "feature_id": "1060",
                    "value": "",
                    "value_int": null,
                    "variant_id": "5665",
                    "feature_type": "S",
                    "internal_name": "Ходовой товар",
                    "description": "Ходовой товар",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Ходовой товар (сезонный)",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "variants": {
                        "5665": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "5665",
                            "variant": "Ходовой товар (сезонный)",
                            "image_pairs": false
                        }
                    }
                },
                "664": {
                    "feature_id": "664",
                    "value": "",
                    "value_int": null,
                    "variant_id": "2889",
                    "feature_type": "S",
                    "internal_name": "Условия отпуска из аптек",
                    "description": "Условия отпуска из аптек",
                    "prefix": "",
                    "suffix": "",
                    "variant": "Без рецепта",
                    "parent_id": "550",
                    "display_on_header": "N",
                    "display_on_catalog": "Y",
                    "display_on_product": "Y",
                    "feature_code": "",
                    "purpose": "find_products",
                    "features_hash": "360-2889",
                    "variants": {
                        "2889": {
                            "value": "",
                            "value_int": null,
                            "variant_id": "2889",
                            "variant": "Без рецепта",
                            "image_pairs": false
                        }
                    }
                }
            },
            "qty_content": [],
            "premoderation_reason": ""
        },
        {
            "product_id": "44848",
            "product": "Артростоп рапид плюс №30 таблетки",
            "supplier_id": null,
            "product_code": "30405",
            "product_type": "P",
            "status": "H",
            "company_id": "9",
            "list_price": "0",
            "amount": "0",
            "weight": "0.000",
            "length": "0",
            "width": "0",
            "height": "0",
            "shipping_freight": "0.00",
            "low_avail_limit": "0",
            "timestamp": "1618892358",
            "updated_timestamp": "1684319040",
            "usergroup_ids": "0",
            "is_edp": "N",
            "edp_shipping": "N",
            "unlimited_download": "N",
            "tracking": "B",
            "free_shipping": "N",
            "zero_price_action": "R",
            "is_pbp": "Y",
            "is_op": "N",
            "is_oper": "N",
            "is_returnable": "Y",
            "return_period": "10",
            "avail_since": "0",
            "out_of_stock_actions": "N",
            "localization": "",
            "min_qty": "0",
            "max_qty": "0",
            "qty_step": "0",
            "list_qty_count": "0",
            "tax_ids": "",
            "age_verification": "N",
            "age_limit": "0",
            "options_type": "P",
            "exceptions_type": "F",
            "details_layout": "default",
            "shipping_params": "a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}",
            "facebook_obj_type": "",
            "parent_product_id": "0",
            "yml2_brand": "",
            "yml2_origin_country": "",
            "yml2_store": "",
            "yml2_pickup": "",
            "yml2_delivery": "",
            "yml2_adult": "N",
            "yml2_delivery_options": null,
            "yml2_bid": "0",
            "yml2_model": "",
            "yml2_sales_notes": "",
            "yml2_type_prefix": "",
            "yml2_offer_type": "",
            "yml2_market_category": "",
            "yml2_manufacturer_warranty": "",
            "yml2_expiry": "",
            "yml2_purchase_price": "0",
            "yml2_description": null,
            "yml2_cpa": "Y",
            "buy_now_url": "",
            "ab__stickers_manual_ids": "",
            "ab__stickers_generated_ids": null,
            "guid": "50d80e75-e6ca-11e7-80c4-0862664d53d6",
            "1c_title": "АРТРОСТОП РАПИД ПЛЮС №30 табл",
            "true_photo": "N",
            "product_group": "1",
            "active_substance_id": "0",
            "pharm_group_id": "440",
            "1c_categories": null,
            "nds": null,
            "supplier_guid": "63087d27-e17f-11e3-a4db-003067a403f0",
            "scode": "80481620",
            "brand": null,
            "handpopularity": "0",
            "master_product_id": "0",
            "master_product_status": "A",
            "master_product_offers_count": "0",
            "price": "515",
            "category_ids": [
                1731
            ],
            "seo_name": "artrostop-rapid-plyus-30-tabletki",
            "seo_path": "1657/1659/1731",
            "average_rating": null,
            "discussion_type": "D",
            "discussion_thread_id": "46454",
            "main_category": 1731,
            "options_type_raw": "P",
            "exceptions_type_raw": "F",
            "tracking_raw": "B",
            "zero_price_action_raw": "R",
            "min_qty_raw": "0",
            "max_qty_raw": "0",
            "qty_step_raw": "0",
            "list_qty_count_raw": "0",
            "details_layout_raw": "default",
            "ab__vg_videos": false,
            "main_pair": {
                "pair_id": "21506",
                "image_id": "0",
                "detailed_id": "23542",
                "position": "0",
                "object_id": "44848",
                "object_type": "product",
                "detailed": {
                    "object_id": "44848",
                    "object_type": "product",
                    "type": "M",
                    "image_path": "https://neman.kg/images/watermarked/detailed/23/Артростоп_рэпид_.webp",
                    "alt": "",
                    "image_x": "1506",
                    "image_y": "1206",
                    "http_image_path": "http://neman.kg/images/watermarked/detailed/23/Артростоп_рэпид_.webp",
                    "https_image_path": "https://neman.kg/images/detailed/23/Артростоп_рэпид_.webp",
                    "absolute_path": "/home/admin/web/neman.kg/public_html/images/watermarked/detailed/23/Артростоп_рэпид_.webp",
                    "relative_path": "detailed/23/Артростоп_рэпид_.webp"
                }
            },
            "base_price": "515",
            "selected_options": [],
            "has_options": false,
            "product_options": [],
            "discounts": {
                "A": 0,
                "P": 0
            },
            "product_features": [],
            "qty_content": [],
            "premoderation_reason": ""
        }
    ]
    export const params= {
        "area": "A",
        "use_caching": true,
        "extend": [
            "product_name",
            "prices",
            "categories",
            "categories"
        ],
        "custom_extend": [],
        "pname": "Y",
        "pshort": "Y",
        "pfull": "Y",
        "pkeywords": "Y",
        "feature": [],
        "type": "simple",
        "page": 1,
        "action": "",
        "filter_variants": [],
        "features_hash": "",
        "limit": 0,
        "bid": 0,
        "match": "all",
        "tracking": [],
        "get_frontend_urls": false,
        "items_per_page": 10,
        "apply_disabled_filters": "",
        "load_products_extra_data": true,
        "storefront": null,
        "company_ids": "",
        "subcats": "Y",
        "pcode_from_q": "Y",
        "search_performed": "Y",
        "hide_out_of_stock_products": false,
        "sort_by": "popularity",
        "sort_order": "desc",
        "usergroup_ids": [
            "7",
            "12"
        ],
        "sort_order_rev": "asc",
        "total_items": "28319"

}